### ISSUE TITLE
Saving Split window setting - not able to save current view 

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#35]
If you adjust the "splits" and select Save... a new split entry is created, even if you enter the name of current split (you now have 2 with same name)

Suggest
- Splits-->Set menu indicates current split
- Rename "Save..." as "Save as..."
- Add menu item "Save" for saving current proportions to current split (does not open a dialog)

**Comment by rcoreilly** [comment]
done

**Comment by rohrlich** [comment]
I reopened because you still don't know which split set is the current one when you invoke the "Set View". Also I envisioned "Save" without a menu as I think of it as saving my current Set.

Leave open as low priority or if you disagree about first comment just close.

**Comment by rcoreilly** [comment]
ok, in there now -- kept the menu on Save but current is highilighted, in case you want to change a different one -- if you're adjusting splitters there is no guarantee it still corresponds to the current one..
